# SPDX-FileCopyrightText: 2021 The meson-python developers
#
# SPDX-License-Identifier: MIT

name: tests

on:
  push:
    branches:
      - main
      - release-*
      - ci-debug-cython-santiy
  pull_request:
    branches:
      - main
      - release-*
    paths:
      # This is spelt like this to do not ignore the docs/examples/ folder.
      - '**'
      - '!docs/**'
      - '!CHANGELOG.rst'
      - '!LICENSE'
      - '!LICENSES/**'
      - '!README.rst'
      - '!.github/workflows/docs.yml'
  workflow_dispatch:
    # Allow to run manually

permissions: {}

env:
  FORCE_COLOR: 1
  PIP_DISABLE_PIP_VERSION_CHECK: 1

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  pixi:
    runs-on: ubuntu-24.04-arm
    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          persist-credentials: false

      - uses: prefix-dev/setup-pixi@f00437f565399d418b0acc85936d12c1fb668347 # v0.10.1
        with:
          pixi-version: v0.77.1
          manifest-path: .github/workflows/pixi.toml
          cache: false

      - name: Install meson-python
        working-directory: .github/workflows
        run: pixi run build

      - name: Run tests
        working-directory: .github/workflows
        run: pixi run test
